/**
 * Next.js middleware: automatic locale detection from Accept-Language header
 *
 * Drop this file at `middleware.ts` (or `src/middleware.ts`) in your Next.js
 * project.  It reads the browser's preferred language from the
 * `Accept-Language` request header and redirects the visitor to the matching
 * locale prefix in your URL structure (e.g. `/de-de/about`).
 *
 * The locale list comes from the `locales.ts` file auto-generated by
 * `@el-j/google-sheet-translations`.  Import it directly:
 *
 * ```ts
 * import { locales, defaultLocale } from '@/i18n/locales'; // generated file
 * ```
 *
 * Quick-start
 * -----------
 * 1. Copy this file to `middleware.ts` at your project root.
 * 2. Replace `SUPPORTED_LOCALES` and `DEFAULT_LOCALE` with your generated values.
 * 3. Adjust the `config.matcher` if your locale-prefixed routes differ.
 *
 * Works with the `resolveLocaleWithFallback` utility exported by
 * `@el-j/google-sheet-translations` for consistent locale resolution logic.
 *
 * @see https://nextjs.org/docs/app/building-your-application/routing/internationalization
 */

import type { NextRequest } from 'next/server';
import { NextResponse } from 'next/server';

// ---------------------------------------------------------------------------
// Configuration – replace with your generated locales
// ---------------------------------------------------------------------------

/**
 * All locale codes produced by @el-j/google-sheet-translations.
 * In a real project, import from the generated locales.ts:
 *   import { locales as SUPPORTED_LOCALES } from '@/i18n/locales';
 */
const SUPPORTED_LOCALES = ['en-us', 'de-de', 'fr-fr', 'es-es', 'it-it', 'ja-jp', 'zh-cn'];

/** Locale to redirect to when no match is found. */
const DEFAULT_LOCALE = 'en-us';

// ---------------------------------------------------------------------------
// Locale detection
// ---------------------------------------------------------------------------

/**
 * Parses an `Accept-Language` header value and returns the best-matching
 * supported locale using the same 3-step strategy as `resolveLocaleWithFallback`:
 *
 * 1. Exact match:          `'en-us'` → `'en-us'`
 * 2. Case-insensitive:     `'EN-US'` → `'en-us'`
 * 3. Language-family:      `'en'` or `'en-gb'` → `'en-us'`
 *
 * Falls back to `DEFAULT_LOCALE` when nothing matches.
 */
function detectLocale(acceptLanguage: string | null): string {
  if (!acceptLanguage) return DEFAULT_LOCALE;

  // Parse quality values: "en-US,en;q=0.9,de;q=0.8"
  const candidates = acceptLanguage
    .split(',')
    .map((part) => {
      const [rawLang, rawQ] = part.trim().split(';q=');
      return {
        lang: rawLang.trim().toLowerCase().replace('_', '-'),
        q: rawQ ? parseFloat(rawQ) : 1,
      };
    })
    .filter((c) => c.lang && !Number.isNaN(c.q))
    .sort((a, b) => b.q - a.q);

  for (const { lang } of candidates) {
    // 1. Exact (case-normalised) match
    if (SUPPORTED_LOCALES.includes(lang)) return lang;
    // 2. Language-family prefix match (e.g. 'en' → 'en-us')
    const prefix = lang.split('-')[0];
    const familyMatch = SUPPORTED_LOCALES.find((l) => l.startsWith(`${prefix}-`) || l === prefix);
    if (familyMatch) return familyMatch;
  }

  return DEFAULT_LOCALE;
}

// ---------------------------------------------------------------------------
// Middleware
// ---------------------------------------------------------------------------

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Skip Next.js internals, API routes, and static assets
  if (
    pathname.startsWith('/_next') ||
    pathname.startsWith('/api') ||
    /\.\w+$/.test(pathname)
  ) {
    return NextResponse.next();
  }

  // If the URL already starts with a supported locale prefix, leave it alone
  const hasLocalePrefix = SUPPORTED_LOCALES.some(
    (locale) => pathname === `/${locale}` || pathname.startsWith(`/${locale}/`),
  );
  if (hasLocalePrefix) return NextResponse.next();

  // Detect the visitor's preferred locale and redirect
  const locale = detectLocale(request.headers.get('accept-language'));
  const url = request.nextUrl.clone();
  url.pathname = `/${locale}${pathname}`;
  return NextResponse.redirect(url);
}

export const config = {
  // Run on all routes except Next.js internals and static files
  matcher: ['/((?!_next/static|_next/image|favicon.ico|.*\\..*).*)'],
};
